apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclientcredentials.k8s.rightcrowd.com
spec:
  group: k8s.rightcrowd.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetSecretName:
                  type: string
                realm:
                  type: string
                clientId:
                  type: string
                fallbackStrategy:
                  type: string
                  enum:
                    - "skip"
                    - "error"
                keys:
                  type: object
                  properties:
                    clientIdProperty:
                      type: string
                    clientSecretProperty:
                      type: string
                    realmProperty:
                      type: string
              required:
                - targetSecretName
            status:
              type: object
              properties:
                latestOperatorStatusUpdate:
                  type: string
      additionalPrinterColumns:
        - name: TargetSecretName
          type: string
          description: The name of the realm
          jsonPath: .spec.targetSecretName
        # - name: Latest Operator Status Update
        #   type: date
        #   description: The date of the last successful sync
        #   jsonPath: .status.latestOperatorStatusUpdate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  names:
    plural: keycloakclientcredentials
    singular: keycloakclientcredential
    kind: KeycloakClientCredential
    shortNames:
    - kccc
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
